project_id = "yqnsrkcnoawvazsrxoyl"

[functions.ai-chatbot]
verify_jwt = true

[functions.auto-generate-invoices]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.order-auto-reject]
verify_jwt = false

[functions.scheduled-disbursement]
verify_jwt = false

[functions.send-notification]
verify_jwt = true

[functions.send-payment-reminder]
verify_jwt = false

[functions.subscription-payment]
verify_jwt = true

[functions.subscription-renewal]
verify_jwt = false

[functions.validate-admin-secret]
verify_jwt = false

[functions.vendor-ai-assistant]
verify_jwt = true

[functions.whatsapp-notification]
verify_jwt = true

[functions.xendit-create-invoice]
verify_jwt = true

[functions.xendit-disbursement]
verify_jwt = true

[functions.xendit-webhook]
verify_jwt = false

[functions.merchant-ai-assistant]
verify_jwt = true
