import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Share2, Copy, Users, Gift, Wallet, Check } from 'lucide-react';
import { toast } from 'sonner';
import { format } from 'date-fns';

interface ReferralDashboardProps {
  userRole: 'merchant' | 'tenant' | 'vendor';
}

export function ReferralDashboard({ userRole }: ReferralDashboardProps) {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [copied, setCopied] = useState(false);

  // Get or create referral code
  const { data: referralData, isLoading } = useQuery({
    queryKey: ['my-referral', user?.id],
    queryFn: async () => {
      if (!user?.id) return null;

      // Check if user has a referral code
      const { data: existing } = await supabase
        .from('referrals')
        .select('*')
        .eq('referrer_user_id', user.id)
        .is('referee_user_id', null)
        .single();

      if (existing) return existing;

      // Create new referral entry (code will be auto-generated by trigger)
      const { data: newReferral, error } = await supabase
        .from('referrals')
        .insert({
          referrer_user_id: user.id,
          referrer_role: userRole,
          status: 'pending',
          referral_code: `REF${Date.now().toString(36).toUpperCase()}`,
        })
        .select()
        .single();

      if (error) throw error;
      return newReferral;
    },
    enabled: !!user?.id,
  });

  // Get referral stats
  const { data: stats } = useQuery({
    queryKey: ['referral-stats', user?.id],
    queryFn: async () => {
      if (!user?.id) return { total: 0, completed: 0, pending: 0 };

      const { data: referrals } = await supabase
        .from('referrals')
        .select('status')
        .eq('referrer_user_id', user.id)
        .not('referee_user_id', 'is', null);

      const total = referrals?.length || 0;
      const completed = referrals?.filter(r => r.status === 'completed').length || 0;
      const pending = referrals?.filter(r => r.status === 'pending').length || 0;

      return { total, completed, pending };
    },
    enabled: !!user?.id,
  });

  // Get rewards
  const { data: rewards = [] } = useQuery({
    queryKey: ['my-rewards', user?.id],
    queryFn: async () => {
      if (!user?.id) return [];

      const { data } = await supabase
        .from('referral_rewards')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      return data || [];
    },
    enabled: !!user?.id,
  });

  const referralLink = referralData?.referral_code
    ? `${window.location.origin}/auth?ref=${referralData.referral_code}`
    : '';

  const handleCopyLink = () => {
    navigator.clipboard.writeText(referralLink);
    setCopied(true);
    toast.success('Referral link copied!');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShareWhatsApp = () => {
    const message = encodeURIComponent(
      `Join SiHuni using my referral link and get special rewards! ${referralLink}`
    );
    window.open(`https://wa.me/?text=${message}`, '_blank');
  };

  const getRewardInfo = () => {
    switch (userRole) {
      case 'merchant':
        return { amount: '20%', description: 'of referee subscription for 6 months when they upgrade' };
      case 'tenant':
        return { amount: 'Rp 25.000', description: 'voucher when your friend pays first rent (+ Rp 25k bonus for 3 consecutive months!)' };
      case 'vendor':
        return { amount: 'Rp 50.000', description: 'cashback when your referral completes 10 orders (+ Rp 100k bonus at 3 months!)' };
      default:
        return { amount: 'Rp 0', description: '' };
    }
  };

  const rewardInfo = getRewardInfo();
  const totalRewards = rewards
    .filter(r => r.status === 'credited')
    .reduce((sum, r) => sum + Number(r.amount), 0);

  if (isLoading) {
    return <div className="text-center py-8">Loading...</div>;
  }

  return (
    <div className="space-y-6">
      {/* Referral Link Card */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Share2 className="h-5 w-5" />
            Your Referral Link
          </CardTitle>
          <CardDescription>
            Share this link and earn {rewardInfo.amount} {rewardInfo.description}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex gap-2">
            <Input value={referralLink} readOnly className="font-mono text-sm" />
            <Button variant="outline" onClick={handleCopyLink}>
              {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            </Button>
          </div>
          <Button className="w-full" onClick={handleShareWhatsApp}>
            <Share2 className="h-4 w-4 mr-2" />
            Share via WhatsApp
          </Button>
        </CardContent>
      </Card>

      {/* Stats Cards */}
      <div className="grid grid-cols-3 gap-4">
        <Card>
          <CardContent className="p-4 text-center">
            <Users className="h-6 w-6 mx-auto mb-2 text-primary" />
            <p className="text-2xl font-bold">{stats?.total || 0}</p>
            <p className="text-xs text-muted-foreground">Total Referrals</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <Gift className="h-6 w-6 mx-auto mb-2 text-green-500" />
            <p className="text-2xl font-bold">{stats?.completed || 0}</p>
            <p className="text-xs text-muted-foreground">Completed</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 text-center">
            <Wallet className="h-6 w-6 mx-auto mb-2 text-yellow-500" />
            <p className="text-2xl font-bold">
              {new Intl.NumberFormat('id-ID', { notation: 'compact' }).format(totalRewards)}
            </p>
            <p className="text-xs text-muted-foreground">Earned</p>
          </CardContent>
        </Card>
      </div>

      {/* Rewards History */}
      <Card>
        <CardHeader>
          <CardTitle>Rewards History</CardTitle>
        </CardHeader>
        <CardContent>
          {rewards.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <Gift className="h-12 w-12 mx-auto mb-4 opacity-50" />
              <p>No rewards yet. Start sharing your referral link!</p>
            </div>
          ) : (
            <div className="space-y-3">
              {rewards.map((reward) => (
                <div key={reward.id} className="flex items-center justify-between p-3 border rounded-lg">
                  <div>
                    <p className="font-medium capitalize">{reward.type.replace('_', ' ')}</p>
                    <p className="text-sm text-muted-foreground">
                      {format(new Date(reward.created_at), 'MMM d, yyyy')}
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="font-semibold">
                      {new Intl.NumberFormat('id-ID', {
                        style: 'currency',
                        currency: 'IDR',
                        minimumFractionDigits: 0,
                      }).format(Number(reward.amount))}
                    </p>
                    <Badge variant={reward.status === 'credited' ? 'default' : 'secondary'}>
                      {reward.status}
                    </Badge>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
