import { supabase } from '@/lib/integrations/supabase/client';
import { Invoice } from '../types';
import { format } from 'date-fns';
import { sendInvoiceNotification } from '@/features/notifications/utils/notifications';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;

export interface CreateInvoicePayload {
  contract_id: string;
  merchant_id: string;
  tenant_user_id: string;
  amount: number;
  tax_amount: number;
  description: string;
  due_date: string;
}

export const merchantInvoiceService = {
  async getInvoices(merchantId: string): Promise<Invoice[]> {
    const { data, error } = await supabase
      .from('invoices')
      .select('*')
      .eq('merchant_id', merchantId)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data as Invoice[];
  },

  async createInvoice(payload: CreateInvoicePayload): Promise<void> {
    const { contract_id, merchant_id, tenant_user_id, amount, tax_amount, description, due_date } = payload;

    // Validate due date is not in the past
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const dueDateObj = new Date(due_date);
    if (dueDateObj < today) {
      throw new Error('Due date cannot be in the past');
    }

    // Check for duplicate invoice (same contract, same month)
    const dueDateMonth = format(dueDateObj, 'yyyy-MM');
    const { data: existingInvoices, error: checkError } = await supabase
      .from('invoices')
      .select('id, due_date')
      .eq('contract_id', contract_id)
      .neq('status', 'cancelled');
    
    if (checkError) throw checkError;
    
    const hasDuplicate = existingInvoices?.some(inv => {
      const invMonth = format(new Date(inv.due_date), 'yyyy-MM');
      return invMonth === dueDateMonth;
    });
    
    if (hasDuplicate) {
      throw new Error('An invoice already exists for this contract in the selected month');
    }

    const { error } = await supabase
      .from('invoices')
      .insert({
        invoice_number: '', // Will be auto-generated by DB trigger/function if configured, or needs to be handled. 
                            // Looking at the original code, it was empty string.
                            // Assuming there is a trigger to generate it or it allows empty.
        contract_id,
        merchant_id,
        tenant_user_id,
        amount,
        tax_amount,
        total_amount: amount + tax_amount,
        description: description.slice(0, 1000),
        due_date,
        status: 'draft',
      });

    if (error) throw error;
  },

  async sendInvoice(invoiceId: string, merchantName: string): Promise<void> {
    // Get invoice details
    const { data: invoice, error: invoiceError } = await supabase
      .from('invoices')
      .select('*')
      .eq('id', invoiceId)
      .single();
    
    if (invoiceError) throw invoiceError;
    if (!invoice) throw new Error('Invoice not found');

    // Get tenant profile for email
    const { data: tenantProfile, error: profileError } = await supabase
      .from('profiles')
      .select('email, full_name')
      .eq('user_id', invoice.tenant_user_id)
      .single();
    
    if (profileError) throw profileError;

    // Update invoice status
    const { error: updateError } = await supabase
      .from('invoices')
      .update({ 
        status: 'sent',
        issued_at: new Date().toISOString(),
      })
      .eq('id', invoiceId);
    
    if (updateError) throw updateError;

    // Send email notification
    try {
      await sendInvoiceNotification(
        tenantProfile.email,
        tenantProfile.full_name || 'Tenant',
        {
          invoiceNumber: invoice.invoice_number,
          merchantName: merchantName,
          amount: Number(invoice.total_amount),
          dueDate: format(new Date(invoice.due_date), 'MMM d, yyyy'),
          description: invoice.description || undefined,
        }
      );
    } catch (emailError) {
      console.error('Failed to send email notification:', emailError);
      // Don't throw - invoice is already sent
    }
  },

  async markAsPaid(invoiceId: string, currentStatus: string): Promise<void> {
    const VALID_STATUS_TRANSITIONS: Record<string, string[]> = {
      draft: ['sent', 'cancelled'],
      sent: ['paid', 'overdue', 'cancelled'],
      overdue: ['paid', 'cancelled'],
      paid: [],
      cancelled: [],
    };

    const allowedTransitions = VALID_STATUS_TRANSITIONS[currentStatus] || [];
    if (!allowedTransitions.includes('paid')) {
      throw new Error(`Cannot mark invoice as paid. Current status: ${currentStatus}`);
    }

    const { error } = await supabase
      .from('invoices')
      .update({ 
        status: 'paid',
        paid_at: new Date().toISOString(),
      })
      .eq('id', invoiceId);

    if (error) throw error;
  },

  async sendPaymentReminder(invoiceId: string, tenantUserId: string): Promise<void> {
    const response = await fetch(`${SUPABASE_URL}/functions/v1/send-payment-reminder`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ 
        invoiceId,
        tenantUserId,
        type: 'manual'
      }),
    });
    
    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.message || 'Failed to send reminder');
    }
  },

  async generatePdf(invoiceId: string): Promise<{ html: string }> {
    const response = await fetch(`${SUPABASE_URL}/functions/v1/generate-invoice-pdf`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ invoiceId }),
    });
    
    if (!response.ok) throw new Error('Failed to generate PDF');
    
    return response.json();
  }
};
